# Copyright Istio Authors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

##################################################################################################
# This file defines secrets, configmaps for AppDynamics Agents Settings.
#
# To apply all of them:
#
#   kubectl apply -f platform/kube/appd.yaml
#
##################################################################################################

##################################################################################################
# AppDynamics Agent Secret
##################################################################################################
apiVersion: v1
kind: Secret
metadata:
  name: appd-agent-secret
type: Opaque
data:
  access-key: eHEyYmJ2b29odTN6
---
##################################################################################################
# AppDynamics Agent Environment Variables
##################################################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: appd-agent-envs
data:
  APPDYNAMICS_AGENT_ACCOUNT_NAME: hopper202105232309044
  APPDYNAMICS_AGENT_APPLICATION_NAME: bookinfo
  APPDYNAMICS_CONTROLLER_HOST_NAME: hopper202105232309044.saas.appdynamics.com
  APPDYNAMICS_CONTROLLER_PORT: "443"
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: "true"
