
##################################################################################################
# Reviews service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app: reviews
    service: reviews
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-reviews
  labels:
    account: reviews
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  labels:
    app: reviews
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      serviceAccountName: bookinfo-reviews
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: reviews
        image: ciscodevcloud/examples-bookinfo-reviews-v1:1.0.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: appd-agent-envs
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        - name: APPDYNAMICS_AGENT_TIER_NAME
          value: "reviews"
        - name: APPDYNAMICS_AGENT_NODE_NAME
          value: "reviews-v1"
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: appd-agent-secret
              key: access-key
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        - name: appd-agent-repo
          mountPath: /opt/appdynamics
        - name: appd-java-agent-log-config
          mountPath: /opt/appdynamics/ver20.8.0.30686/conf/logging
        securityContext:
          runAsUser: 1000
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: appd-agent-repo
        emptyDir: {}
      - name: appd-java-agent-log-config
        configMap:
          name: appd-java-agent-log-config
      initContainers:
      - command:
        - cp
        - -r
        - /opt/appdynamics/.
        - /opt/temp
        name: appd-agent
        image: docker.io/appdynamics/java-agent:20.8.0
        volumeMounts:
        - mountPath: /opt/temp
          name: appd-agent-repo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  labels:
    app: reviews
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v2
  template:
    metadata:
      labels:
        app: reviews
        version: v2
    spec:
      serviceAccountName: bookinfo-reviews
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: reviews
        image: ciscodevcloud/examples-bookinfo-reviews-v2:1.0.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: appd-agent-envs
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        - name: APPDYNAMICS_AGENT_TIER_NAME
          value: "reviews"
        - name: APPDYNAMICS_AGENT_NODE_NAME
          value: "reviews-v2"
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: appd-agent-secret
              key: access-key
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        - name: appd-agent-repo
          mountPath: /opt/appdynamics
        - name: appd-java-agent-log-config
          mountPath: /opt/appdynamics/ver20.8.0.30686/conf/logging
        securityContext:
          runAsUser: 1000
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: appd-agent-repo
        emptyDir: {}
      - name: appd-java-agent-log-config
        configMap:
          name: appd-java-agent-log-config
      initContainers:
      - command:
        - cp
        - -r
        - /opt/appdynamics/.
        - /opt/temp
        name: appd-agent
        image: docker.io/appdynamics/java-agent:20.8.0
        volumeMounts:
        - mountPath: /opt/temp
          name: appd-agent-repo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v3
  labels:
    app: reviews
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v3
  template:
    metadata:
      labels:
        app: reviews
        version: v3
    spec:
      serviceAccountName: bookinfo-reviews
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: reviews
        image: ciscodevcloud/examples-bookinfo-reviews-v3:1.0.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: appd-agent-envs
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        - name: APPDYNAMICS_AGENT_TIER_NAME
          value: "reviews"
        - name: APPDYNAMICS_AGENT_NODE_NAME
          value: "reviews-v3"
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: appd-agent-secret
              key: access-key
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        - name: appd-agent-repo
          mountPath: /opt/appdynamics
        - name: appd-java-agent-log-config
          mountPath: /opt/appdynamics/ver20.8.0.30686/conf/logging
        securityContext:
          runAsUser: 1000
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: appd-agent-repo
        emptyDir: {}
      - name: appd-java-agent-log-config
        configMap:
          name: appd-java-agent-log-config
      initContainers:
      - command:
        - cp
        - -r
        - /opt/appdynamics/.
        - /opt/temp
        name: appd-agent
        image: docker.io/appdynamics/java-agent:20.8.0
        volumeMounts:
        - mountPath: /opt/temp
          name: appd-agent-repo
---
