app_name: bookinfo
tier_name: details-service
node_name: details-service-v2
controller:
  host: <your_account_name>.saas.appdynamics.com
  port: 443
  account: <your_account_name>
  access_key: <your_access_key>
  use_ssl: true
  log_dir: /tmp/
